__precompile__(true)

module DUNEatLapp

using DelimitedFiles
using DataFrames
using Random
using Distributions
using CSV
using Clustering
using ProgressBars
using HDF5
using StatsBase
using Distances

export greet_DUNEatLapp
export get_evts_index
export apply_E_resolution
export apply_std_E_resolution
export get_sampling
export get_bin_centers 
export get_n_primaries
export get_number_of_events
export get_rate_neutron_captures_Ar
export get_info_neutron_captures_Ar
export get_primary_vertex
export E_MainCluster
export get_clusters_energy_of_evt
export get_clusters_vertex_and_energy_of_evt
export process_clustering_neutron_file
export full_process_clustering_neutron_file
export full_process_clustering_file_active
export get_capture_position
export is_n_capture_on_Ar
export Single_Hits_lardon
export Single_Hits_lardon_old
export nbr_cluster
export E_MainCluster_and_NbrofDiscrimination_Emin
export E_MainCluster_and_NbrofDiscrimination_Emin_ArCascade
export get_hits_in_active_LAr_TPC
export get_hits_in_inactive_LAr
export get_clusters_vertex_and_energy_of_evt_space_time
export find_n_clusters_in_radius
export get_hits_in_active_LAr_TPC_Lateral_fidu
export moving_window_filter
export Create_df_Main_Cluster_Discrimination_Emin
export create_df_vectors_for_costheta
export Main_Cluster
export Compute_Sun_initialVector

include("functions.jl")
include("clustering_g4.jl")
include("G4_connector.jl")
include("neutron_capture_info.jl")
include("analyse_lardon.jl")

end
